### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Dotquard** [TwiDev/SpectralDamage#1]
Hello, I just discovered your plug and I liked it personally, but I will make some suggestions for a few color features that can come and do not look simple, for example yellow after 100 damage after 100 damage like rainbow

**Comment by TwiDev** [comment]
Hello,
Thank you very much for your suggestion.
It's indeed an interesting feature that could be implemented in the plugin in a few days!
I will think about it and find the best way to implement it in the plugin
