### ISSUE TITLE
Harming potion damage

### ISSUE THREAD

**Issue by Momonche** [TwiDev/SpectralDamage#10]
**Describe the bug**
When I throw a harming potion on a player, there is no damage indicator

**To Reproduce**
Throw a harming potion on a player

**Expected behavior**
Display damage

**Comment by TwiDev** [comment]
Hello, 

It's because this feature is not yet implemented in the plugin. 

But thank you for your suggestion, it is very likely that this feature will be available in a new version of the plugin

**Comment by TwiDev** [comment]
The functionality is done and should appear in the next version of the plugin which will be released shortly
