### ISSUE TITLE
Damage less than a specific value does not summon damage indicator text.

### ISSUE THREAD

**Issue by EisiaDEV** [TwiDev/SpectralDamage#11]
**Is your feature request related to a problem? Please describe.**

no.

**Describe the solution you'd like**

Damage less than a specific value does not summon damage indicator text.

**Describe alternatives you've considered**

Damage less than a specific value does not summon damage indicator text - Do not invoke the damage indicator if the value is retrieved from the inside of the config file and damage less than that value is applied.

ex)
- minimum-damage: 1 → If the damage is less than 1, the damage indicator is not summoned.

**Additional context**

**Comment by TwiDev** [comment]
Hello,

 Thank you for your suggestion, it is very likely that this feature will be available in a new version of the plugin

**Comment by TwiDev** [comment]
The functionality is done and should appear in the next version of the plugin which will be released shortly
