### ISSUE TITLE
turn off the choke damage display on the armor stand

### ISSUE THREAD

**Issue by HANNAAN1288** [TwiDev/SpectralDamage#12]
I would like to ask a question, can I turn off the choke damage display on the armor stand?

**Comment by TwiDev** [comment]
Hello,

I don't really understand your issue, can you describe it further?

**Comment by HANNAAN1288** [comment]
Like this.
The armor stand will display damage by suffocation.
![image](https://github.com/TwiDev/SpectralDamage/assets/108947333/1e7443db-f9c8-404e-b262-54ac0f9c41db)

**Comment by TwiDev** [comment]
Hello !
sorry for the late response. 

I plan to do a pretty big update in 1 to 2 weeks which should fix this bug. because I have very little time available, 
Thank you very much for your issue I will investigate the problem!

**Comment by HANNAAN1288** [comment]
Oh I see.
Thank you very much!!

**Comment by TwiDev** [comment]
The bug is normally fixed and should appear in the next version of the plugin which will be released shortly
