### ISSUE TITLE
damage not showing correctly

### ISSUE THREAD

**Issue by McGrimpus** [TwiDev/SpectralDamage#19]
**Describe the bug**
When you hit a player with a sword and he's wearing an armor. The damage shown is not accurate as if the damage is the same when you hit a person without armor. An accurate damage would help and please make it compatible with java 8 because most 1.8 players use java 8 to host their server.

**To Reproduce**
1. Hit a player with an armor

**Expected behavior**
I Thought it was going to show an accurate damage

**Screenshots**
no screenshot

**Desktop (please complete the following information):**
 - WINDOWS
 - Chrome

**Comment by TwiDev** [comment]
Hi, thanks for the issue !
this is planned to be fixed for the next update
