### ISSUE TITLE
Support for Paper 1.20.6 with no CB relocation

### ISSUE THREAD

**Issue by HaHaWTH** [TwiDev/SpectralDamage#21]
**Is your feature request related to a problem? Please describe.**
Since Paper has removed CB relocation in 1.20.6, SpectralDamage cannot detect its nms version and will disable itself.

**Describe the solution you'd like**
Solutions can be referred to PaperMC fourm: https://forums.papermc.io/threads/important-dev-psa-future-removal-of-cb-package-relocation.1106/

**Comment by TwiDev** [comment]
Hello
Thank for your issue
I will start working on this by tomorrow!

**Comment by Nymphxyz** [comment]
Any progress would be very appreciated!

**Comment by TwiDev** [comment]
Developer Note :
Hello,
It's been a while!

Minecraft support version 1.21 will be released around August 15
I have read all your suggestions and I will make a version with each of them but it will take me some time as I have other projects to work on at the moment, I will keep you posted
