### ISSUE TITLE
Add new to enable or disable damage indicator

### ISSUE THREAD

**Issue by NockyCZ** [TwiDev/SpectralDamage#5]
Can u please add these commands please ?
/spectraldamage enable PLAYER
/spectraldamage disable PLAYER

**Comment by TwiDev** [comment]
Hello,
Thank you for your feedback !
Yes of course the feature will be added to the plugin in a few days

**Comment by NockyCZ** [comment]
Thank you :)

**Comment by TwiDev** [comment]
Hello,
The feature has been deployed on the latest version of the plugin available on spigot!
