### ISSUE TITLE
[Feature] Healing Indicators

### ISSUE THREAD

**Issue by LadyHaley** [TwiDev/SpectralDamage#7]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
The plugin page didnt showcase the following. Please add healing indicators for when an entity gains health
**Describe alternatives you've considered**

**Additional context**

**Comment by TwiDev** [comment]
Hi thank you for your feedback,
All the new features you suggest me will be added in an update that will be release next week
