### ISSUE TITLE
WorldGuard Support

### ISSUE THREAD

**Issue by smhcnshn** [TwiDev/SpectralDamage#8]
Damage Indicators still show up inside wg regions that deny pvp, WG Support could be added to tackle the issue

**Comment by TwiDev** [comment]
Hello,
I released a new version of the plugin which should resolve your issue.

I first tried to fix the problem without using world guard. If this doesn't work for you I will integrate world guard

if you encounter compatibility problems between versions of minecraft or any problems with the plugin, please please post in the discussion thread or in github issues
