### ISSUE TITLE
1.20.2 Compatability

### ISSUE THREAD

**Issue by smhcnshn** [TwiDev/SpectralDamage#9]
Hello the plugin does not work on version 1.20.2, here is the stacktrace: https://mclo.gs/BVCekzz could you please add support for it?

**Comment by TwiDev** [comment]
Hello,
I released a new version of the plugin which should resolve your issue.

if you encounter compatibility problems between versions of minecraft or any problems with the plugin, please please post in the discussion thread or in github issues

**Comment by smhcnshn** [comment]
isnt here the github issues?

**Comment by TwiDev** [comment]
Yes but if even after this fix you still have compatability problems you can create a new issue.
